// import house1 from "../assets/house.jpg";
// import house2 from "./assets/housekitchen.jpg";
// import house3 from "../assets/houseliving.jpg";
import house1 from "../assets/house.jpg"
// import house2 from "../assets/housekitchen.jpg"
// import house3  from "../assets/huthouse1.jpg"
export const data = [
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  {
    id: 1,
    name: "Samsung Galaxy M14 5G",
    price: 13999,
    category: "Electronics",
    image1: house1,
    image2: house1,
    image3: house1,
  },
  // {
  //   id: 2,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 3,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 4,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 5,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 6,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 7,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 8,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 9,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 10,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 10,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 11,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 12,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 13,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // },
  // {
  //   id: 14,
  //   name: "Samsung Galaxy M14 5G",
  //   price: 13999,
  //   category: "Electronics",
  //   image1: house1,
  //   image2: house2,
  //   image3: house3,
  // }
  
];
